# Q1

In [30]:
#how to create an empty and a full NumPy array:

import numpy as np

#empty array
arr1 = np.empty((4,5))
arr1

#explanation:creates an array without initializing its values.

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.89144350e-307, 7.56587584e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 2.78149851e-307, 1.06811422e-306,
        8.45590539e-307, 6.23054972e-307],
       [1.11260687e-306, 1.69118108e-306, 1.42418987e-306,
        2.22522596e-306, 9.34610469e-307]])

In [19]:
#full array
arr1 = np.full((3,3),3)
arr1

#explanation:creates an array filled with a specified value.

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

# Q2

In [17]:
#create a numpy array filled with all zeroes:

arr1 = np.zeros([4, 3])   
arr1

#explanation:creates an array of zeros with the specified shape.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Q3

In [20]:
#create a numpy array filled with all ones:

arr1 = np.ones([4, 3])   
arr1
 
#explanation:creates an array of ones with the specified shape.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Q4

In [27]:
#check whether a numpy array contains a specific row:

arr1 = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([4,5,6])
arr2 = any(np.array(arr1))
if arr2 :
    print("Row exists.")
else:
    print("Row does not exist.")
    
#explanation: It checks if any row in the array is equal to the specified row.

Row exists.


# Q5

In [121]:
#how to remove rows in numpy array that contains non-numeric values:

arr1 = np.array([[1,2,3],[4,'a',6],[3,2,1]])
remove = [0,1]
arr2 = np.delete(arr1, remove, axis=0)
print("original array")
print(arr1)
print("after removing specified row:")
print(arr2)

#explanation:It removes rows containing NaN(Not a Number) values.

original array
[['1' '2' '3']
 ['4' 'a' '6']
 ['3' '2' '1']]
after removing specified row:
[['3' '2' '1']]


# Q6

In [71]:
#remove single-dimensional entries from the shape of an array:

arr1 = np.array([[[1, 2, 3]]])
reshape_arr1 = np.ravel(arr1).reshape(-1)
print("removed single dimensional entries:")
print(reshape_arr1)

#explanation:it converts multi-dimensional into one-dimensional

removed single dimensional entries:
[1 2 3]


# Q7

In [85]:
#find the number of occurrences of a sequence in a numpy array:

arr1 = np.array([1,2,3,4,6,1,2,3,5,8])
arr2 = repr(arr1).count("1, 2, 3")
print(arr2)

#explanation:It finds the number of occurrences of the specified sequence.

2


# Q8

In [101]:
#find the most frequent value in a numpy array:

arr1 = np.array([1,2,2,4,5,2]) 
print(np.bincount(arr1).argmax())

#explanation: It finds the value with the highest frequency.

2


# Q9

In [99]:
#combining a one and a two-dimensional numpy array:

arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6], [7, 8, 9]])
arr3 = np.vstack((arr1, arr2))
print(arr3)

#explanation:it stacks arrays vertically.

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Q10

In [100]:
#how to build an array of all combinations of two numpy array:

arr1 = np.array([1,2])
arr2 = np.array([3,4])
arr3 = np.array(np.meshgrid(arr1, arr2)).T.reshape(-1,2)
print(arr3)

#explanation: Creates a mesh of all combinations of elements from arr1 and arr2.

[[1 3]
 [1 4]
 [2 3]
 [2 4]]


# FUNCTIONS IN NUMPY

In [ ]:
#LISTS OF FUNCTIONS ARE:
function1 = np.transpose
function2 = np.ravel
function3 = np.ones
function4 = np.zeroes
function5 = np.concatenate
function6 = np.vstack
function7 = np.hstack

# function 1 - np.transpose

In [104]:
#EXPLANATION: Transpose is use when we need to change dimensions in a 2D array. It works with 2D inputs.

import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr1 = np.transpose(arr1)
arr1

#in these example it changes the rows and columns in 2*3 array.

array([[1, 4],
       [2, 5],
       [3, 6]])

# function 2 - np.ravel

In [105]:
#EXPLANATION: Ravel is used when we need a flattened copy of the array. If the array is already 1D it is unnecessary.

arr1 = np.array([[1, 2, 3],
                [4, 5, 6]])

arr1 = np.ravel(arr1)
arr1

#in these example the 2*3 array is flattened into 1D array.

array([1, 2, 3, 4, 5, 6])

# function 3 - np.ones

In [106]:
#EXPLANATION: Ones is used when we need an array filled with ones and that also of a specific shape.

arr1 = np.ones((2, 3))
arr1

#in these example 2*3 array is created which is filled with ones.

array([[1., 1., 1.],
       [1., 1., 1.]])

# function 4 - np.zeroes

In [108]:
#EXPLANATION: Zeroes is used when we need an array filled with zeroes and that also of a specific shape.

arr1 = np.zeros((2,3))
arr1

#in these example 2*3 array is created which is filled with zeroes.

array([[0., 0., 0.],
       [0., 0., 0.]])

# function 5 - np.concatenate

In [112]:
#EXPLANATION: Concatenate is used when we want to join the array by connecting then horizantally or vertically.

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6]])
arr3 = np.concatenate((arr1, arr2), axis=0)
arr3

#in these example arr1 and arr2 are concatenated along with axis 0 which results in 2*2 array.

array([[1, 2],
       [3, 4],
       [5, 6]])

# function 6 - np.vstack

In [114]:
#EXPLANATION: vstack is used when we want virtically stack array with the same number of columns.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.vstack((arr1, arr2))
arr3

#in these example arr1 and arr2 are vertically stacked and it creats 2*3 array.

array([[1, 2, 3],
       [4, 5, 6]])

# function 7 - np.hstack

In [115]:
#EXPLANATION: hstack is used when we want horizontally stack array with the same number of rows.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.hstack((arr1, arr2))
arr3

#in these example arr1 and arr2 are horizontally stacked and it creats 1D array.

array([1, 2, 3, 4, 5, 6])